# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sickboy/projects/Swarm_Ryan_Rigidity

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sickboy/projects/Swarm_Ryan_Rigidity

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/sickboy/projects/Swarm_Ryan_Rigidity && $(CMAKE_COMMAND) -E cmake_progress_start /home/sickboy/projects/Swarm_Ryan_Rigidity/CMakeFiles /home/sickboy/projects/Swarm_Ryan_Rigidity/PebbleRigidityTest/CMakeFiles/progress.marks
	cd /home/sickboy/projects/Swarm_Ryan_Rigidity && $(MAKE) -f CMakeFiles/Makefile2 PebbleRigidityTest/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sickboy/projects/Swarm_Ryan_Rigidity/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/sickboy/projects/Swarm_Ryan_Rigidity && $(MAKE) -f CMakeFiles/Makefile2 PebbleRigidityTest/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/sickboy/projects/Swarm_Ryan_Rigidity && $(MAKE) -f CMakeFiles/Makefile2 PebbleRigidityTest/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/sickboy/projects/Swarm_Ryan_Rigidity && $(MAKE) -f CMakeFiles/Makefile2 PebbleRigidityTest/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/sickboy/projects/Swarm_Ryan_Rigidity && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
PebbleRigidityTest/CMakeFiles/Test.dir/rule:
	cd /home/sickboy/projects/Swarm_Ryan_Rigidity && $(MAKE) -f CMakeFiles/Makefile2 PebbleRigidityTest/CMakeFiles/Test.dir/rule
.PHONY : PebbleRigidityTest/CMakeFiles/Test.dir/rule

# Convenience name for target.
Test: PebbleRigidityTest/CMakeFiles/Test.dir/rule
.PHONY : Test

# fast build rule for target.
Test/fast:
	cd /home/sickboy/projects/Swarm_Ryan_Rigidity && $(MAKE) -f PebbleRigidityTest/CMakeFiles/Test.dir/build.make PebbleRigidityTest/CMakeFiles/Test.dir/build
.PHONY : Test/fast

# Convenience name for target.
PebbleRigidityTest/CMakeFiles/pebble.dir/rule:
	cd /home/sickboy/projects/Swarm_Ryan_Rigidity && $(MAKE) -f CMakeFiles/Makefile2 PebbleRigidityTest/CMakeFiles/pebble.dir/rule
.PHONY : PebbleRigidityTest/CMakeFiles/pebble.dir/rule

# Convenience name for target.
pebble: PebbleRigidityTest/CMakeFiles/pebble.dir/rule
.PHONY : pebble

# fast build rule for target.
pebble/fast:
	cd /home/sickboy/projects/Swarm_Ryan_Rigidity && $(MAKE) -f PebbleRigidityTest/CMakeFiles/pebble.dir/build.make PebbleRigidityTest/CMakeFiles/pebble.dir/build
.PHONY : pebble/fast

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	cd /home/sickboy/projects/Swarm_Ryan_Rigidity && $(MAKE) -f PebbleRigidityTest/CMakeFiles/Test.dir/build.make PebbleRigidityTest/CMakeFiles/Test.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	cd /home/sickboy/projects/Swarm_Ryan_Rigidity && $(MAKE) -f PebbleRigidityTest/CMakeFiles/Test.dir/build.make PebbleRigidityTest/CMakeFiles/Test.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	cd /home/sickboy/projects/Swarm_Ryan_Rigidity && $(MAKE) -f PebbleRigidityTest/CMakeFiles/Test.dir/build.make PebbleRigidityTest/CMakeFiles/Test.dir/main.c.s
.PHONY : main.c.s

pebbleRigidity.o: pebbleRigidity.c.o
.PHONY : pebbleRigidity.o

# target to build an object file
pebbleRigidity.c.o:
	cd /home/sickboy/projects/Swarm_Ryan_Rigidity && $(MAKE) -f PebbleRigidityTest/CMakeFiles/pebble.dir/build.make PebbleRigidityTest/CMakeFiles/pebble.dir/pebbleRigidity.c.o
.PHONY : pebbleRigidity.c.o

pebbleRigidity.i: pebbleRigidity.c.i
.PHONY : pebbleRigidity.i

# target to preprocess a source file
pebbleRigidity.c.i:
	cd /home/sickboy/projects/Swarm_Ryan_Rigidity && $(MAKE) -f PebbleRigidityTest/CMakeFiles/pebble.dir/build.make PebbleRigidityTest/CMakeFiles/pebble.dir/pebbleRigidity.c.i
.PHONY : pebbleRigidity.c.i

pebbleRigidity.s: pebbleRigidity.c.s
.PHONY : pebbleRigidity.s

# target to generate assembly for a file
pebbleRigidity.c.s:
	cd /home/sickboy/projects/Swarm_Ryan_Rigidity && $(MAKE) -f PebbleRigidityTest/CMakeFiles/pebble.dir/build.make PebbleRigidityTest/CMakeFiles/pebble.dir/pebbleRigidity.c.s
.PHONY : pebbleRigidity.c.s

pebble_external_facade.o: pebble_external_facade.c.o
.PHONY : pebble_external_facade.o

# target to build an object file
pebble_external_facade.c.o:
	cd /home/sickboy/projects/Swarm_Ryan_Rigidity && $(MAKE) -f PebbleRigidityTest/CMakeFiles/pebble.dir/build.make PebbleRigidityTest/CMakeFiles/pebble.dir/pebble_external_facade.c.o
.PHONY : pebble_external_facade.c.o

pebble_external_facade.i: pebble_external_facade.c.i
.PHONY : pebble_external_facade.i

# target to preprocess a source file
pebble_external_facade.c.i:
	cd /home/sickboy/projects/Swarm_Ryan_Rigidity && $(MAKE) -f PebbleRigidityTest/CMakeFiles/pebble.dir/build.make PebbleRigidityTest/CMakeFiles/pebble.dir/pebble_external_facade.c.i
.PHONY : pebble_external_facade.c.i

pebble_external_facade.s: pebble_external_facade.c.s
.PHONY : pebble_external_facade.s

# target to generate assembly for a file
pebble_external_facade.c.s:
	cd /home/sickboy/projects/Swarm_Ryan_Rigidity && $(MAKE) -f PebbleRigidityTest/CMakeFiles/pebble.dir/build.make PebbleRigidityTest/CMakeFiles/pebble.dir/pebble_external_facade.c.s
.PHONY : pebble_external_facade.c.s

vertices.o: vertices.c.o
.PHONY : vertices.o

# target to build an object file
vertices.c.o:
	cd /home/sickboy/projects/Swarm_Ryan_Rigidity && $(MAKE) -f PebbleRigidityTest/CMakeFiles/pebble.dir/build.make PebbleRigidityTest/CMakeFiles/pebble.dir/vertices.c.o
.PHONY : vertices.c.o

vertices.i: vertices.c.i
.PHONY : vertices.i

# target to preprocess a source file
vertices.c.i:
	cd /home/sickboy/projects/Swarm_Ryan_Rigidity && $(MAKE) -f PebbleRigidityTest/CMakeFiles/pebble.dir/build.make PebbleRigidityTest/CMakeFiles/pebble.dir/vertices.c.i
.PHONY : vertices.c.i

vertices.s: vertices.c.s
.PHONY : vertices.s

# target to generate assembly for a file
vertices.c.s:
	cd /home/sickboy/projects/Swarm_Ryan_Rigidity && $(MAKE) -f PebbleRigidityTest/CMakeFiles/pebble.dir/build.make PebbleRigidityTest/CMakeFiles/pebble.dir/vertices.c.s
.PHONY : vertices.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Test"
	@echo "... edit_cache"
	@echo "... pebble"
	@echo "... rebuild_cache"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... pebbleRigidity.o"
	@echo "... pebbleRigidity.i"
	@echo "... pebbleRigidity.s"
	@echo "... pebble_external_facade.o"
	@echo "... pebble_external_facade.i"
	@echo "... pebble_external_facade.s"
	@echo "... vertices.o"
	@echo "... vertices.i"
	@echo "... vertices.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/sickboy/projects/Swarm_Ryan_Rigidity && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

